/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorDTO;
import org.openapitools.client.model.UserAccountChangeppPatchRequest;
import org.openapitools.client.model.UserAccountChgusernamePatchRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountApi
 */
@Disabled
public class AccountApiTest {

    private final AccountApi api = new AccountApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userAccountChangeppPatchTest() throws ApiException {
        UserAccountChangeppPatchRequest userAccountChangeppPatchRequest = null;
        api.userAccountChangeppPatch(userAccountChangeppPatchRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userAccountChgusernamePatchTest() throws ApiException {
        UserAccountChgusernamePatchRequest userAccountChgusernamePatchRequest = null;
        api.userAccountChgusernamePatch(userAccountChgusernamePatchRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userDisconnectPostTest() throws ApiException {
        api.userDisconnectPost();
        // TODO: test validations
    }

}
