/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorDTO;
import org.openapitools.client.model.UserChangeThemePatchRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppearanceApi
 */
@Disabled
public class AppearanceApiTest {

    private final AppearanceApi api = new AppearanceApi();

    /**
     * Change user theme
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void userChangeThemePatchTest() throws ApiException {
        UserChangeThemePatchRequest userChangeThemePatchRequest = null;
        api.userChangeThemePatch(userChangeThemePatchRequest);
        // TODO: test validations
    }

}
