/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

/**
 * Model tests for DiscussionsCreatePostRequest
 */
public class DiscussionsCreatePostRequestTest {

    /**
     * Model tests for DiscussionsCreatePostRequest
     */
    @Test
    public void testDiscussionsCreatePostRequest() {
        // Create an instance of DiscussionsCreatePostRequest with example values
        DiscussionsCreatePostRequest request = new DiscussionsCreatePostRequest();
        request.setUser("alice@acme");

        // Check that the 'user' property has been set correctly
        assertEquals("alice@acme", request.getUser());
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // Create an instance of DiscussionsCreatePostRequest and set the 'user' property to
        DiscussionsCreatePostRequest request = new DiscussionsCreatePostRequest();
        request.setUser("alice@acme");

        // Check that the 'user' property has been set correctly
        assertEquals("alice@acme", request.getUser());
    }

}
