/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserChangeThemePatchRequest
 */
public class UserChangeThemePatchRequestTest {
    private final UserChangeThemePatchRequest model = new UserChangeThemePatchRequest();

    /**
     * Model tests for UserChangeThemePatchRequest
     */
    @Test
    public void testUserChangeThemePatchRequest() {
        // TODO: test UserChangeThemePatchRequest
    }

    /**
     * Test the property 'themeId'
     */
    @Test
    public void themeIdTest() {
        // TODO: test themeId
    }

}
