/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserSettingsDTO
 */
public class UserSettingsDTOTest {
    private final UserSettingsDTO model = new UserSettingsDTO();

    /**
     * Model tests for UserSettingsDTO
     */
    @Test
    public void testUserSettingsDTO() {
        // TODO: test UserSettingsDTO
    }

    /**
     * Test the property 'theme'
     */
    @Test
    public void themeTest() {
        // TODO: test theme
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'unreadBadges'
     */
    @Test
    public void unreadBadgesTest() {
        // TODO: test unreadBadges
    }

    /**
     * Test the property 'notificationSound'
     */
    @Test
    public void notificationSoundTest() {
        // TODO: test notificationSound
    }

    /**
     * Test the property 'profileImage'
     */
    @Test
    public void profileImageTest() {
        // TODO: test profileImage
    }

}
