/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.DiscussionDTO;
import io.swagger.client.model.DiscussionsCreateBody;
import io.swagger.client.model.ErrorDTO;
import io.swagger.client.model.MessageDTO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for MessagingApi
 */
@Ignore
public class MessagingApiTest {

    private final MessagingApi api = new MessagingApi();

    /**
     * Create a new discussion
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void discussionsCreatePostTest() throws Exception {
        DiscussionsCreateBody body = null;
        api.discussionsCreatePost(body);

        // TODO: test validations
    }
    /**
     * Get all messages in a conversation
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void discussionsDiscussionIdMessagesGetTest() throws Exception {
        Integer discussionId = null;
        List<MessageDTO> response = api.discussionsDiscussionIdMessagesGet(discussionId);

        // TODO: test validations
    }
    /**
     * Send a message in a disccusion
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void discussionsDiscussionIdMessagesPostTest() throws Exception {
        MessageDTO body = null;
        Integer discussionId = null;
        api.discussionsDiscussionIdMessagesPost(body, discussionId);

        // TODO: test validations
    }
    /**
     * Get a list of all discussions
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void discussionsGetTest() throws Exception {
        List<DiscussionDTO> response = api.discussionsGet();

        // TODO: test validations
    }
}
