/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ChangePasswordDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ChangePasswordDTO {
  public static final String SERIALIZED_NAME_OLDPASSWORD = "oldpassword";
  @SerializedName(SERIALIZED_NAME_OLDPASSWORD)
  private String oldpassword;

  public static final String SERIALIZED_NAME_NEWPASSWORD = "newpassword";
  @SerializedName(SERIALIZED_NAME_NEWPASSWORD)
  private String newpassword;

  public ChangePasswordDTO() {
  }

  public ChangePasswordDTO oldpassword(String oldpassword) {
    
    this.oldpassword = oldpassword;
    return this;
  }

   /**
   * Get oldpassword
   * @return oldpassword
  **/
  @javax.annotation.Nullable
  public String getOldpassword() {
    return oldpassword;
  }


  public void setOldpassword(String oldpassword) {
    this.oldpassword = oldpassword;
  }


  public ChangePasswordDTO newpassword(String newpassword) {
    
    this.newpassword = newpassword;
    return this;
  }

   /**
   * Get newpassword
   * @return newpassword
  **/
  @javax.annotation.Nullable
  public String getNewpassword() {
    return newpassword;
  }


  public void setNewpassword(String newpassword) {
    this.newpassword = newpassword;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangePasswordDTO changePasswordDTO = (ChangePasswordDTO) o;
    return Objects.equals(this.oldpassword, changePasswordDTO.oldpassword) &&
        Objects.equals(this.newpassword, changePasswordDTO.newpassword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oldpassword, newpassword);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangePasswordDTO {\n");
    sb.append("    oldpassword: ").append(toIndentedString(oldpassword)).append("\n");
    sb.append("    newpassword: ").append(toIndentedString(newpassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("oldpassword");
    openapiFields.add("newpassword");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ChangePasswordDTO
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChangePasswordDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChangePasswordDTO is not found in the empty JSON string", ChangePasswordDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ChangePasswordDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ChangePasswordDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("oldpassword") != null && !jsonObj.get("oldpassword").isJsonNull()) && !jsonObj.get("oldpassword").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `oldpassword` to be a primitive type in the JSON string but got `%s`", jsonObj.get("oldpassword").toString()));
      }
      if ((jsonObj.get("newpassword") != null && !jsonObj.get("newpassword").isJsonNull()) && !jsonObj.get("newpassword").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `newpassword` to be a primitive type in the JSON string but got `%s`", jsonObj.get("newpassword").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChangePasswordDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChangePasswordDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChangePasswordDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChangePasswordDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<ChangePasswordDTO>() {
           @Override
           public void write(JsonWriter out, ChangePasswordDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChangePasswordDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ChangePasswordDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ChangePasswordDTO
  * @throws IOException if the JSON string is invalid with respect to ChangePasswordDTO
  */
  public static ChangePasswordDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChangePasswordDTO.class);
  }

 /**
  * Convert an instance of ChangePasswordDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

