/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DiscussionsCreatePostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DiscussionsCreatePostRequest {
  public static final String SERIALIZED_NAME_USER1 = "user1";
  @SerializedName(SERIALIZED_NAME_USER1)
  private String user1;

  public static final String SERIALIZED_NAME_USER2 = "user2";
  @SerializedName(SERIALIZED_NAME_USER2)
  private String user2;

  public DiscussionsCreatePostRequest() {
  }

  public DiscussionsCreatePostRequest user1(String user1) {
    
    this.user1 = user1;
    return this;
  }

   /**
   * Get user1
   * @return user1
  **/
  @javax.annotation.Nonnull
  public String getUser1() {
    return user1;
  }


  public void setUser1(String user1) {
    this.user1 = user1;
  }


  public DiscussionsCreatePostRequest user2(String user2) {
    
    this.user2 = user2;
    return this;
  }

   /**
   * Get user2
   * @return user2
  **/
  @javax.annotation.Nonnull
  public String getUser2() {
    return user2;
  }


  public void setUser2(String user2) {
    this.user2 = user2;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiscussionsCreatePostRequest discussionsCreatePostRequest = (DiscussionsCreatePostRequest) o;
    return Objects.equals(this.user1, discussionsCreatePostRequest.user1) &&
        Objects.equals(this.user2, discussionsCreatePostRequest.user2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user1, user2);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiscussionsCreatePostRequest {\n");
    sb.append("    user1: ").append(toIndentedString(user1)).append("\n");
    sb.append("    user2: ").append(toIndentedString(user2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("user1");
    openapiFields.add("user2");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("user1");
    openapiRequiredFields.add("user2");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to DiscussionsCreatePostRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DiscussionsCreatePostRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DiscussionsCreatePostRequest is not found in the empty JSON string", DiscussionsCreatePostRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DiscussionsCreatePostRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DiscussionsCreatePostRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DiscussionsCreatePostRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("user1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user1").toString()));
      }
      if (!jsonObj.get("user2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user2").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DiscussionsCreatePostRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DiscussionsCreatePostRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DiscussionsCreatePostRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DiscussionsCreatePostRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DiscussionsCreatePostRequest>() {
           @Override
           public void write(JsonWriter out, DiscussionsCreatePostRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DiscussionsCreatePostRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DiscussionsCreatePostRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DiscussionsCreatePostRequest
  * @throws IOException if the JSON string is invalid with respect to DiscussionsCreatePostRequest
  */
  public static DiscussionsCreatePostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DiscussionsCreatePostRequest.class);
  }

 /**
  * Convert an instance of DiscussionsCreatePostRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

