/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * NotificationsDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class NotificationsDTO {
  public static final String SERIALIZED_NAME_SOUNDS = "sounds";
  @SerializedName(SERIALIZED_NAME_SOUNDS)
  private String sounds;

  public static final String SERIALIZED_NAME_BADGES = "badges";
  @SerializedName(SERIALIZED_NAME_BADGES)
  private String badges;

  public NotificationsDTO() {
  }

  public NotificationsDTO sounds(String sounds) {
    
    this.sounds = sounds;
    return this;
  }

   /**
   * Get sounds
   * @return sounds
  **/
  @javax.annotation.Nullable
  public String getSounds() {
    return sounds;
  }


  public void setSounds(String sounds) {
    this.sounds = sounds;
  }


  public NotificationsDTO badges(String badges) {
    
    this.badges = badges;
    return this;
  }

   /**
   * Get badges
   * @return badges
  **/
  @javax.annotation.Nullable
  public String getBadges() {
    return badges;
  }


  public void setBadges(String badges) {
    this.badges = badges;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationsDTO notificationsDTO = (NotificationsDTO) o;
    return Objects.equals(this.sounds, notificationsDTO.sounds) &&
        Objects.equals(this.badges, notificationsDTO.badges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sounds, badges);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationsDTO {\n");
    sb.append("    sounds: ").append(toIndentedString(sounds)).append("\n");
    sb.append("    badges: ").append(toIndentedString(badges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sounds");
    openapiFields.add("badges");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to NotificationsDTO
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NotificationsDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NotificationsDTO is not found in the empty JSON string", NotificationsDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NotificationsDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NotificationsDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("sounds") != null && !jsonObj.get("sounds").isJsonNull()) && !jsonObj.get("sounds").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sounds` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sounds").toString()));
      }
      if ((jsonObj.get("badges") != null && !jsonObj.get("badges").isJsonNull()) && !jsonObj.get("badges").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `badges` to be a primitive type in the JSON string but got `%s`", jsonObj.get("badges").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NotificationsDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NotificationsDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NotificationsDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NotificationsDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<NotificationsDTO>() {
           @Override
           public void write(JsonWriter out, NotificationsDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NotificationsDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of NotificationsDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of NotificationsDTO
  * @throws IOException if the JSON string is invalid with respect to NotificationsDTO
  */
  public static NotificationsDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NotificationsDTO.class);
  }

 /**
  * Convert an instance of NotificationsDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

