/*
 * CPOO Server API
 * This is a prototype of CPOO Project's front/back API. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@mightycode.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * NotificationsDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-09-26T12:57:02.907739491Z[GMT]")

public class NotificationsDTO {
  @SerializedName("sounds")
  private String sounds = null;

  @SerializedName("badges")
  private String badges = null;

  public NotificationsDTO sounds(String sounds) {
    this.sounds = sounds;
    return this;
  }

   /**
   * Get sounds
   * @return sounds
  **/
  @Schema(description = "")
  public String getSounds() {
    return sounds;
  }

  public void setSounds(String sounds) {
    this.sounds = sounds;
  }

  public NotificationsDTO badges(String badges) {
    this.badges = badges;
    return this;
  }

   /**
   * Get badges
   * @return badges
  **/
  @Schema(description = "")
  public String getBadges() {
    return badges;
  }

  public void setBadges(String badges) {
    this.badges = badges;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationsDTO notificationsDTO = (NotificationsDTO) o;
    return Objects.equals(this.sounds, notificationsDTO.sounds) &&
        Objects.equals(this.badges, notificationsDTO.badges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sounds, badges);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationsDTO {\n");
    
    sb.append("    sounds: ").append(toIndentedString(sounds)).append("\n");
    sb.append("    badges: ").append(toIndentedString(badges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
